/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/_system'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as SystemIndexRouteImport } from './routes/_system/index'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as SystemSettingsIndexRouteImport } from './routes/_system/settings/index'
import { Route as SystemSettingsBillingRouteImport } from './routes/_system/settings/billing'
import { Route as SystemOnboardingPlansRouteImport } from './routes/_system/onboarding/plans'
import { Route as SystemBillingSuccessRouteImport } from './routes/_system/billing/success'

const SystemRoute = SystemRouteImport.update({
  id: '/_system',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const SystemSettingsIndexRoute = SystemSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSettingsBillingRoute = SystemSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => SystemRoute,
} as any)
const SystemOnboardingPlansRoute = SystemOnboardingPlansRouteImport.update({
  id: '/onboarding/plans',
  path: '/onboarding/plans',
  getParentRoute: () => SystemRoute,
} as any)
const SystemBillingSuccessRoute = SystemBillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => SystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/': typeof SystemIndexRoute
  '/billing/success': typeof SystemBillingSuccessRoute
  '/onboarding/plans': typeof SystemOnboardingPlansRoute
  '/settings/billing': typeof SystemSettingsBillingRoute
  '/settings': typeof SystemSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/': typeof SystemIndexRoute
  '/billing/success': typeof SystemBillingSuccessRoute
  '/onboarding/plans': typeof SystemOnboardingPlansRoute
  '/settings/billing': typeof SystemSettingsBillingRoute
  '/settings': typeof SystemSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_system': typeof SystemRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_system/': typeof SystemIndexRoute
  '/_system/billing/success': typeof SystemBillingSuccessRoute
  '/_system/onboarding/plans': typeof SystemOnboardingPlansRoute
  '/_system/settings/billing': typeof SystemSettingsBillingRoute
  '/_system/settings/': typeof SystemSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/billing/success'
    | '/onboarding/plans'
    | '/settings/billing'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/billing/success'
    | '/onboarding/plans'
    | '/settings/billing'
    | '/settings'
  id:
    | '__root__'
    | '/_public'
    | '/_system'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/_system/'
    | '/_system/billing/success'
    | '/_system/onboarding/plans'
    | '/_system/settings/billing'
    | '/_system/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  SystemRoute: typeof SystemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_system': {
      id: '/_system'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_system/': {
      id: '/_system/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_system/settings/': {
      id: '/_system/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SystemSettingsIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/_system/settings/billing': {
      id: '/_system/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SystemSettingsBillingRouteImport
      parentRoute: typeof SystemRoute
    }
    '/_system/onboarding/plans': {
      id: '/_system/onboarding/plans'
      path: '/onboarding/plans'
      fullPath: '/onboarding/plans'
      preLoaderRoute: typeof SystemOnboardingPlansRouteImport
      parentRoute: typeof SystemRoute
    }
    '/_system/billing/success': {
      id: '/_system/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof SystemBillingSuccessRouteImport
      parentRoute: typeof SystemRoute
    }
  }
}

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface SystemRouteChildren {
  SystemIndexRoute: typeof SystemIndexRoute
  SystemBillingSuccessRoute: typeof SystemBillingSuccessRoute
  SystemOnboardingPlansRoute: typeof SystemOnboardingPlansRoute
  SystemSettingsBillingRoute: typeof SystemSettingsBillingRoute
  SystemSettingsIndexRoute: typeof SystemSettingsIndexRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemIndexRoute: SystemIndexRoute,
  SystemBillingSuccessRoute: SystemBillingSuccessRoute,
  SystemOnboardingPlansRoute: SystemOnboardingPlansRoute,
  SystemSettingsBillingRoute: SystemSettingsBillingRoute,
  SystemSettingsIndexRoute: SystemSettingsIndexRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  SystemRoute: SystemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
