import { Hono } from "hono";
import type { Context } from "hono";
import { env } from "../../env.js";
import { getTenantAuth, requireRole } from "../../lib/middleware/auth.js";
import { jsonError, HTTP_STATUS, ERROR_MESSAGES } from "../../lib/http.js";
import { stripe } from "../../lib/stripe.js";
import { addonEligiblePlan } from "../../features/ai/entitlement.js";

// Purchase-specific: the subscription must be active or trialing to add an item.
const ADDON_ACTIVE_STATUSES = ["active", "trialing"] as const;

type AddonOrganization = {
  stripeSubscriptionId: string | null;
  planStatus: string | null;
  plan: string | null;
  aiAddonActive: boolean;
};

/**
 * Validates every precondition required to purchase the AI add-on. Shared by
 * the purchase (`POST`) and preview (`GET`) routes so both enforce an identical
 * gate. Returns a `jsonError` Response when a precondition fails, or `null`
 * when the organization is eligible to add the add-on.
 */
function assertAddonPurchasable(
  c: Context,
  organization: AddonOrganization,
): Response | null {
  if (!organization.stripeSubscriptionId) {
    return jsonError(
      c,
      HTTP_STATUS.BAD_REQUEST,
      "no_active_subscription",
      "An active subscription is required before adding the AI add-on.",
    );
  }

  if (
    !ADDON_ACTIVE_STATUSES.includes(
      organization.planStatus as (typeof ADDON_ACTIVE_STATUSES)[number],
    )
  ) {
    return jsonError(
      c,
      HTTP_STATUS.PAYMENT_REQUIRED,
      "subscription_not_active",
      "Your subscription must be active or trialing to add the AI add-on.",
    );
  }

  if (!addonEligiblePlan(organization.plan)) {
    return jsonError(
      c,
      HTTP_STATUS.FORBIDDEN,
      "plan_not_eligible",
      "The AI add-on is only available on the PREMIUM and ENTERPRISE plans.",
    );
  }

  if (organization.aiAddonActive) {
    return jsonError(
      c,
      HTTP_STATUS.CONFLICT,
      "ai_addon_already_active",
      "The AI add-on is already active for this organization.",
    );
  }

  return null;
}

/**
 * AI add-on lifecycle. The add-on is modeled as a SECOND subscription item on
 * the existing subscription — never a second subscription. These routes only
 * mutate Stripe; the `aiAddonActive` / `aiAddonSubscriptionItemId` entitlement
 * columns are derived exclusively from webhooks, so the response is a
 * `pending` acknowledgement (the flag flips once Stripe emits the webhook).
 */
export const aiAddonRoute = new Hono()
  .get("/ai-addon/preview", requireRole("super_admin"), async (c) => {
    try {
      const { organization } = getTenantAuth(c);

      const precondition = assertAddonPurchasable(c, organization);
      if (precondition) return precondition;

      const subscription = await stripe.subscriptions.retrieve(
        organization.stripeSubscriptionId!,
      );

      const currency = subscription.currency;

      // Preview updating the subscription to include the add-on item alongside
      // the existing items. Existing items are referenced by id so Stripe keeps
      // them intact and only prices the incremental add-on.
      const existingItems = subscription.items.data.map((item) => ({
        id: item.id,
      }));

      const preview = await stripe.invoices.createPreview({
        subscription: subscription.id,
        subscription_details: {
          items: [
            ...existingItems,
            { price: env.STRIPE_AI_ADDON_PRICE_KEY },
          ],
          proration_behavior: "create_prorations",
        },
      });

      // Amount due now = the sum of the proration line items generated by
      // adding the add-on mid-cycle.
      const prorationAmount = (preview.lines?.data ?? [])
        .filter((line) => line.proration)
        .reduce((sum, line) => sum + line.amount, 0);

      // Recurring amount = the add-on price's unit amount in the subscription's
      // currency (the price is multi-currency).
      const price = await stripe.prices.retrieve(env.STRIPE_AI_ADDON_PRICE_KEY, {
        expand: ["currency_options"],
      });
      const recurringAmount =
        price.currency_options?.[currency]?.unit_amount ??
        (price.currency === currency ? price.unit_amount : null) ??
        price.unit_amount ??
        0;

      const nextBillingDate = new Date(
        subscription.current_period_end * 1000,
      ).toISOString();

      return c.json({
        currency,
        prorationAmount,
        recurringAmount,
        nextBillingDate,
      });
    } catch (error) {
      console.error("Error previewing AI add-on:", error);
      return jsonError(
        c,
        HTTP_STATUS.INTERNAL_SERVER_ERROR,
        ERROR_MESSAGES.INTERNAL_SERVER_ERROR,
        error instanceof Error ? error.message : "Unknown error",
      );
    }
  })
  .post("/ai-addon", requireRole("super_admin"), async (c) => {
    try {
      const { organization } = getTenantAuth(c);

      const precondition = assertAddonPurchasable(c, organization);
      if (precondition) return precondition;

      await stripe.subscriptionItems.create({
        subscription: organization.stripeSubscriptionId!,
        price: env.STRIPE_AI_ADDON_PRICE_KEY,
        quantity: 1,
      });

      return c.json({
        status: "pending",
        message:
          "AI add-on purchase started. It will activate once payment is confirmed.",
      });
    } catch (error) {
      console.error("Error adding AI add-on:", error);
      return jsonError(
        c,
        HTTP_STATUS.INTERNAL_SERVER_ERROR,
        ERROR_MESSAGES.INTERNAL_SERVER_ERROR,
        error instanceof Error ? error.message : "Unknown error",
      );
    }
  })
  .delete("/ai-addon", requireRole("super_admin"), async (c) => {
    try {
      const { organization } = getTenantAuth(c);

      if (!organization.aiAddonSubscriptionItemId) {
        return jsonError(
          c,
          HTTP_STATUS.CONFLICT,
          "ai_addon_not_active",
          "There is no active AI add-on to cancel.",
        );
      }

      await stripe.subscriptionItems.del(
        organization.aiAddonSubscriptionItemId,
        { proration_behavior: "create_prorations" },
      );

      return c.json({
        status: "pending",
        message:
          "AI add-on cancellation started. It will be removed once confirmed.",
      });
    } catch (error) {
      console.error("Error removing AI add-on:", error);
      return jsonError(
        c,
        HTTP_STATUS.INTERNAL_SERVER_ERROR,
        ERROR_MESSAGES.INTERNAL_SERVER_ERROR,
        error instanceof Error ? error.message : "Unknown error",
      );
    }
  });
