import { HTTP_STATUS } from "../../lib/http.js";

export const API_ERROR_STATUS_CODE_MAP: Record<
  number,
  (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS]
> = {
  [HTTP_STATUS.BAD_REQUEST]: HTTP_STATUS.BAD_REQUEST,
  [HTTP_STATUS.UNAUTHORIZED]: HTTP_STATUS.UNAUTHORIZED,
  [HTTP_STATUS.FORBIDDEN]: HTTP_STATUS.FORBIDDEN,
  [HTTP_STATUS.NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [HTTP_STATUS.CONFLICT]: HTTP_STATUS.CONFLICT,
  [HTTP_STATUS.UNPROCESSABLE_ENTITY]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
} as const;
